### ISSUE TITLE
Test suite crashed on specific JSON response.

### ISSUE THREAD

**Issue by rivierasolutions** [krajzeg/chaplain#12]
My test returns a response in the format 

```
{ "redirect_uri": "http://some-redirect-uri-here" }
```

I also set up ignoring the property like so:

```
config({
        server: myServer,
        json: { ignore: [ '$.redirect_uri' ] }
    });
```

When I bless the output and run the test again I get:

```
====[ get-safe-redirect-uri:allow-access threw an exception (whoops!) ]=======
====[ HTTP GET /development/saferedirect ]====================================       
string.replace is not a function 
TypeError: string.replace is not a function
    at applyIgnores (C:\Users\Piotr\AppData\Roaming\npm\node_modules\chaplain\dist\lib\plugins\format-text.js:45:23)
    at Array.map (native)
    at Object.compare (C:\Users\Piotr\AppData\Roaming\npm\node_modules\chaplain\dist\lib\plugins\format-text.js:18:26)
    at C:\Users\Piotr\AppData\Roaming\npm\node_modules\chaplain\dist\lib\index.js:167:28
    at tryCatcher (C:\Users\Piotr\AppData\Roaming\npm\node_modules\chaplain\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Piotr\AppData\Roaming\npm\node_modules\chaplain\node_modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (C:\Users\Piotr\AppData\Roaming\npm\node_modules\chaplain\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (C:\Users\Piotr\AppData\Roaming\npm\node_modules\chaplain\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (C:\Users\Piotr\AppData\Roaming\npm\node_modules\chaplain\node_modules\bluebird\js\release\promise.js:683:18)
    at Promise._fulfill (C:\Users\Piotr\AppData\Roaming\npm\node_modules\chaplain\node_modules\bluebird\js\release\promise.js:628:18)
    at PromiseArray._resolve (C:\Users\Piotr\AppData\Roaming\npm\node_modules\chaplain\node_modules\bluebird\js\release\promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (C:\Users\Piotr\AppData\Roaming\npm\node_modules\chaplain\node_modules\bluebird\js\release\promise_array.js:143:14)
    at Promise._settlePromise (C:\Users\Piotr\AppData\Roaming\npm\node_modules\chaplain\node_modules\bluebird\js\release\promise.js:564:26)
    at Promise._settlePromise0 (C:\Users\Piotr\AppData\Roaming\npm\node_modules\chaplain\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (C:\Users\Piotr\AppData\Roaming\npm\node_modules\chaplain\node_modules\bluebird\js\release\promise.js:683:18)
    at Async._drainQueue (C:\Users\Piotr\AppData\Roaming\npm\node_modules\chaplain\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (C:\Users\Piotr\AppData\Roaming\npm\node_modules\chaplain\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Piotr\AppData\Roaming\npm\node_modules\chaplain\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

```

**Comment by rivierasolutions** [comment]
Update: not ignoring the property does't affect the result.

**Comment by krajzeg** [comment]
Looks like the response was actually treated as plaintext, not JSON for some reason (probably a content-type header). Still, a bug in there. Will check. Seems you're finding them faster than I can swat'em 😓

**Comment by krajzeg** [comment]
@rivierasolutions Is this on 0.3.4, or master? Also, more info on what the test was doing would be helpful - did you use {json: true} and what are the headers actually returned in the response?

**Comment by krajzeg** [comment]
This commit: https://github.com/krajzeg/chaplain/commit/2bc57a349908eabbd863f01eb4198b7a4444f11f should at least make it not throw in such situations. Still, your content might have been mistakenly treated as text/plain when it should be JSON, so there might still be a bug lurking somewhere. Please let me know if you figure out why the content was treated as such or can give me more info.

**Comment by rivierasolutions** [comment]
Hah, you were right, the server does actually return JSON with a content-type of 'text/plain'. It was a bug on my end, but one you need to consider nevertheless :)

**Comment by krajzeg** [comment]
It's a weird behavior on the part of `request`, which ignores everything when you pass {json: true} (including what the server claims the response to be) and parses the stuff. Regardless, this shouldn't break chaplain now and should be fixed on master by https://github.com/krajzeg/chaplain/commit/2bc57a349908eabbd863f01eb4198b7a4444f11f.
