### ISSUE TITLE
Add the ability to console.log in before and after

### ISSUE THREAD

**Issue by rivierasolutions** [krajzeg/chaplain#9]
I would like to have some ability to debug my before and after methods. Right now if I try to console.log in `before()` I get an error 

```
chaplain.tests.js:49
                       console.log([ 'Hello: ', world].join(''));
                       ^
 ReferenceError: console is not defined
    at Request._callback (chaplain.tests.js:49:24)
    at Request.self.callback (C:\Users\Piotr\AppData\Roaming\npm\node_modules\chaplain\node_modules\request\request.js:199:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (C:\Users\Piotr\AppData\Roaming\npm\node_modules\chaplain\node_modules\request\request.js:1036:10)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (C:\Users\Piotr\AppData\Roaming\npm\node_modules\chaplain\node_modules\request\request.js:963:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
```

**Comment by krajzeg** [comment]
Missed it since all globals have to be manually exported to the sandbox the testfile runs in. Will fix shortly.

**Comment by krajzeg** [comment]
Should be fixed on master, but please note that console.log will still not work inside the code under test (it is explicitly replaced with a no-op to prevent application logs from being mixed with chaplain output).
